SVC_PREFIX={{ .Prefix }}
NAME = $(SVC_PREFIX){{ .ShortName }}::scss

.PHONY: clean
clean:
	@echo "$(NAME)::clean"
	rm -rf ./node_modules

.PHONY: build
build:
	@echo "$(NAME)::build"
	yarn run scss
	mkdir -p ../assets/css
	cp dist/main.css ../assets/css/main.css
	mkdir -p ../assets/webfonts
	cp -r node_modules/@fortawesome/fontawesome-free/webfonts/* ../assets/webfonts/
