SVC_PREFIX={{ .Prefix }}
NAME = $(SVC_PREFIX){{ .ShortName }}::ui

.PHONY: build
build:
	@echo "$(NAME)::build"
	cd ../.. && $(MAKE) tools-sync-elmc
	../../_tools/bin/elm make src/Main.elm --optimize --output ../assets/elm.js
	../../_tools/bin/elm make src/Main.elm --debug --output ../assets/elm-debug.js

