ELM_FILES = $(shell find . -path ./elm-stuff -prune -o -type f -name '*.elm')

default: $(ELM_FILES)
	elm-make --yes src/Main.elm --output ../assets/main.js

clean-deps:
	rm -rf elm-stuff

clean:
	rm -f *.js
	rm -rf elm-stuff/build-artifacts

run:
	elm-reactor

